# ==============================
#  Server (服务基础配置)
# ==============================
server:
  app_mode: "debug"        # 运行模式: debug(开发), release(生产-日志少性能高)
  http_port: ":8081"       # 端口号: 用户服务建议用 8081 (网关8080, 题目8082)
  service_name: "user-service" # 服务名称 (用于日志打印或注册中心)

# ==============================
#  MySQL (数据库配置)
# ==============================
mysql:
  db_host: "127.0.0.1"     # 数据库地址
  db_port: "3306"          # 端口
  db_user: "root"          # 用户名
  db_password: "root"      # 密码
  db_name: "user_db"
# ==============================
#  Redis (缓存配置)
# ==============================
redis:
  addr: "127.0.0.1:6379"   # 地址
  password: ""             # 密码 (没有就留空)
  db: 0                    # 数据库索引 (0-15)，用户服务默认用 0

email:
  smtp_host: "smtp.qq.com"
  smtp_email: "2847944739@qq.com"
  smtp_pass: "xaystzrlzsaudcic"
